### ISSUE TITLE
RStudio crashes 

### ISSUE THREAD

**Issue by rfsaldanha** [rfsaldanha/brclimr#1]
Some users reported that RStudio crashes after using package functions.

**Comment by rfsaldanha** [comment]
Possible related to DuckDB issue #6231 https://github.com/duckdb/duckdb/issues/6231 affecting Windows users.

The use of `httpfs` is needed to query Parquet files on S3 storage,

**Comment by rfsaldanha** [comment]
I created a new branch with a temporary solution for Windows users, by querying the parquet files on S3 buckets using `arrow` package functions. The query time is slower than the `duckdb` approach.

**Comment by rfsaldanha** [comment]
I pulled the `arrow` branch as the main branch to present a working solution for all operational systems.

The `duckdb` approach, which is faster, is now kept in a separate branch until the issue with compiling `duckdb` extensions for Windows is solved.

**Comment by tallysfeldens** [comment]
Raphael, tudo bem? Antes de mais nada quero dizer que sou sua fã, e uso e recomendo os pacotes que vc faz.
Agora, eu queria uma opinião sua por favor. Eu criei um loop para pegar informações de temperatura de um vetor de municípios, e ele funciona bem, no entanto, está apresentando este erro, saberia me dar uma dica do que posso fazer para resolver? Ele gera meu objeto com as temperaturas, mas não tenho certeza se estão completas porque ao final, ele retorna este erro.

meu loop: 

tmin_hist1 <- data.frame()
> for (i in code_v){
+   j <- fetch_data(code_muni = as.numeric(i), product = "brdwgd", 
+                   indicator = "tmin", statistics = "mean", 
+                   date_start = as.Date("1961-01-01"), date_end = as.Date("1980-12-31"))
+   x <- c(i)
+   id <- rep(x, times = nrow(j))
+   k <- as.data.frame(cbind(id,j))
+   tmin_hist1 <- as.data.frame(rbind(k, tmin_hist1))

Error in `compute.arrow_dplyr_query()`:
! IOError: google::cloud::Status(UNAVAILABLE: Retry policy exhausted in Read(): PerformWork() - CURL error [35]=SSL connect error)

Obrigada!

**Comment by rfsaldanha** [comment]
Olá Tallys, movi sua mensagem para uma nova issue #4

**Comment by rfsaldanha** [comment]
A extensão `httpfs` está funcionando bem no Windows na versão mais recente do DuckDB.
