### ISSUE TITLE
Google Cloud unavailable

### ISSUE THREAD

**Issue by rfsaldanha** [rfsaldanha/brclimr#4]
Raphael, tudo bem? Antes de mais nada quero dizer que sou sua fã, e uso e recomendo os pacotes que vc faz.
Agora, eu queria uma opinião sua por favor. Eu criei um loop para pegar informações de temperatura de um vetor de municípios, e ele funciona bem, no entanto, está apresentando este erro, saberia me dar uma dica do que posso fazer para resolver? Ele gera meu objeto com as temperaturas, mas não tenho certeza se estão completas porque ao final, ele retorna este erro.

meu loop: 

tmin_hist1 <- data.frame()
> for (i in code_v){
+   j <- fetch_data(code_muni = as.numeric(i), product = "brdwgd", 
+                   indicator = "tmin", statistics = "mean", 
+                   date_start = as.Date("1961-01-01"), date_end = as.Date("1980-12-31"))
+   x <- c(i)
+   id <- rep(x, times = nrow(j))
+   k <- as.data.frame(cbind(id,j))
+   tmin_hist1 <- as.data.frame(rbind(k, tmin_hist1))

Error in `compute.arrow_dplyr_query()`:
! IOError: google::cloud::Status(UNAVAILABLE: Retry policy exhausted in Read(): PerformWork() - CURL error [35]=SSL connect error)

Obrigada!

_Originally posted by @tallysfeldens in https://github.com/rfsaldanha/brclimr/issues/1#issuecomment-1534386854_

**Comment by rfsaldanha** [comment]
Olá Tallys,

Bem estranho o erro, mas pela mensagem me parece o seguinte. Interrnamente, o pacote consulta uma base de dados que está hospedada no Google Cloud. Parece que em alguma iteração do loop, não foi possível estabeler conexão com o Google Cloud. Isso pode ter sido uma falha de conexão no lado do servidor (google) ou no cliente (seu computador). Para evitar isso, você deve incluir no seu loop estruturas para tentar novamente caso aconteça algum erro, talvez os comandos `try` e `trycatch` possam ser úteis.

De qualquer forma, eu não recomendo que você consuma esses dados em um loop. Acho que a função que criei no pacote é útil para consultar uma cidade isoladamente e ter a informação rápida.

Para consultar varias cidades e ter mais opções, recomendo você baixar os arquivos parquet na sua máquina e fazer a consulta localmente. Será mais rápido e a possibilidade de erros bem menor.  Nessa página eu escrevi um exemplo sobre como fazer isso.

https://rfsaldanha.github.io/brclimr/articles/parquet_files.html#query-example

**Comment by tallysfeldens** [comment]
Obrigada Raphael!

**Comment by rfsaldanha** [comment]
A versão atual do pacote não utiliza mas o storage da Google Cloud, passando a usar a Digital Ocean Spaces S3.
