### ISSUE TITLE
Dúvida sobre os dados de precipitação

### ISSUE THREAD

**Issue by pedrorenanm** [rfsaldanha/brclimr#5]
Olá, Rafael. Tudo bem?

[Primeiramente, parabéns pelo trabalho]

Estou usando o pacote brclimR para avaliar a precipitação acumulada de um município. No entanto, observando os dados para a estatística pr_sum (BR-DWGD) verifiquei precipitações diárias acima 1000mm, por exemplo. Também busquei o pr_max e verifiquei que os valores são mais aderentes, mas fiquei em dúvida se poderia utiliza-lo para calcular a precipitação acumulada em um determinado mês.

Minha dúvida é se preciso realizar algum tratamento nos valores de pr_sum antes de utiliza-lo, pois, se eu agrupar por mês e somá-lo os valores ficam muito elevados e incoerentes. Minha outra dúvida seria se posso utilizar o pr_max para calcular a precipitação acumulada já que os valores são mais aderentes a realidade..

Segue meu código abaixo:

```
library(brclimr)
library(tidyverse)
library(arrow)
library(lubridate)

pr_data <- open_dataset(sources = "Banco de dados/Clima/parquet_pr.parquet")
pr_data %>% #glimpse()
  filter(code_muni %in% c(1502152,1502772), name == "pr_sum") %>%
  collect() %>% #transform into df
  mutate_at(vars(code_muni),as.factor) %>%
  mutate(year = year(date), month = month(date)) %>%
  filter(year>2009) %>%
  group_by(code_muni,year,month) %>%
  mutate(sum_pr = sum(value)) %>% distinct(code_muni,year,month,sum_pr) %>% ungroup() %>%
  mutate(day = "1",new_date = make_date(year,month,day),code_muni = as_factor(code_muni)) %>%
  select(-day,-month,-year) %>%
  #glimpse()
  ggplot(aes(new_date,sum_pr))+geom_point()+geom_line()+
  scale_x_date(date_breaks = "6 months",date_labels = "%b %y")+
  facet_grid(vars(code_muni))
```

**Comment by rfsaldanha** [comment]
Oi Pedro,

Esses valores relativamente "altos" de precipitação são esperados de acordo com a estatística zonal utilizada. 

A estatística de chuva de média vai considerar todas as células que se sobrepõem ao polígino do município para calcular a média. Já estatísticas como máximo e mínimo selecionam uma célula conforme o valor.

No caso da estatística soma, o valores de todas as células que intersectam o município são somadas. Daí os valores altos, é uma estimativa do volume total de chuva que incidiu no município naquela data.

**Comment by pedrorenanm** [comment]
Entendi, agora sei qual estatística utilizar. Muito obrigado e, mais uma vez, parabéns pelo trabalho incrível!
